### PR TITLE
Bump gradle to 6.8

### PR DESCRIPTION
**Pull request by Goooler**
Gradle 6.8 enhanced Kotlin DSL script performance, see [Release Note](https://docs.gradle.org/6.8/release-notes.html) here

### CODE REVIEW

**Comment by ben-manes** [comment]
Looks like it failed the tests. [Gradle 6.5](https://docs.gradle.org/6.5/release-notes.html#dependency-management-improvements) changed its version detection logic (for the worse in our use-case) and that might be the culprit. You'd have to either debug the test cases or, if not enough interest, close this issue.

**Comment by Goooler** [comment]
> Looks like it failed the tests. [Gradle 6.5](https://docs.gradle.org/6.5/release-notes.html#dependency-management-improvements) changed its version detection logic (for the worse in our use-case) and that might be the culprit. You'd have to either debug the test cases or, if not enough interest, close this issue.

Ok

**Comment by ben-manes** [comment]
Oh, it looks like @jaredsburrows hard coded the gradle upgrade string.

```
Gradle release-candidate updates:
  - Gradle: [6.3 -> 6.8]
```

I think that is an oversight in those new tests, because it will fail whenever a new release occurs. This failed now because the base version is upgraded.

I think the right fix here is to remove that using `checkForGradleUpdate = false` so that the test doesn't check the gradle version.

**Comment by anuraaga** [comment]
I think when updating Gradle we need to add more test versions here too

https://www.github.com/ben-manes/gradle-versions-plugin/tree/master/src%2Ftest%2Fgroovy%2Fcom%2Fgithub%2Fbenmanes%2Fgradle%2Fversions%2FDifferentGradleVersionsSpec.groovy

Or the new Gradle might break sometimes on one or the unrested Gradle versions

**Comment by jaredsburrows** [comment]
@ben-manes @anuraaga PR to fix this - https://github.com/ben-manes/gradle-versions-plugin/pull/468

**Comment by jaredsburrows** [comment]
Can this PR be updated (with the fix)? This PR needs to run `gradlew wrapper` to update the bat/bash scripts.

**Comment by jaredsburrows** [comment]
@Goooler Thanks for sending this in! I really appreciate it but I needed to fix/future poof a test for this PR to work. I did this in #469. Looking forward to your future contributions!

**Comment by Goooler** [comment]
> @Goooler Thanks for sending this in! I really appreciate it but I needed to fix/future poof a test for this PR to work. I did this in #469. Looking forward to your future contributions!

Thx

**Pull request closed without merging**
