### PR TITLE
254 closure output formatter doesnt print std report

### PR DESCRIPTION
**Pull request by Blackbaud-JasonBodnar**

### CODE REVIEW

**Comment by Blackbaud-JasonBodnar** [comment]
This is a fix for #254 .

**Comment by ben-manes** [comment]
Thanks!

**Comment by Blackbaud-JasonBodnar** [comment]
Warning: My fix may have introduced or uncovered an existing bug. When I run the task using the released version everything works fine. When I run the task using jitpack and the hash of my commit that fixed the issue I get:

org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':dependencyUpdates'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:110)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.OutputDirectoryCreatingTaskExecuter.execute(OutputDirectoryCreatingTaskExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.ResolveTaskOutputCachingStateExecuter.execute(ResolveTaskOutputCachingStateExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:101)
        at org.gradle.api.internal.tasks.execution.FinalizeInputFilePropertiesTaskExecuter.execute(FinalizeInputFilePropertiesTaskExecuter.java:44)
        at org.gradle.api.internal.tasks.execution.CleanupStaleOutputsExecuter.execute(CleanupStaleOutputsExecuter.java:91)
        at org.gradle.api.internal.tasks.execution.ResolveTaskArtifactStateTaskExecuter.execute(ResolveTaskArtifactStateTaskExecuter.java:62)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:59)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:54)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.run(EventFiringTaskExecuter.java:51)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:46)
        at org.gradle.execution.taskgraph.LocalTaskInfoExecutor.execute(LocalTaskInfoExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:277)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareWorkItemExecutor.execute(DefaultTaskExecutionGraph.java:262)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:135)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker$1.execute(DefaultTaskPlanExecutor.java:130)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.execute(DefaultTaskPlanExecutor.java:200)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.executeWithWork(DefaultTaskPlanExecutor.java:191)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor$ExecutorWorker.run(DefaultTaskPlanExecutor.java:130)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
Caused by: java.lang.NullPointerException: Cannot get property 'class' on null object
        at com.github.benmanes.gradle.versions.updates.gradle.GradleUpdateResult.<init>(GradleUpdateResult.groovy:56)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdatesReporter.buildGradleUpdateResults(DependencyUpdatesReporter.groovy:176)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdatesReporter.buildBaseObject(DependencyUpdatesReporter.groovy:162)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdatesReporter.write(DependencyUpdatesReporter.groovy:101)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdatesReporter$write.call(Unknown Source)
        at com.github.benmanes.gradle.versions.updates.DependencyUpdatesTask.dependencyUpdates(DependencyUpdatesTask.groovy:72)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.doExecute(StandardTaskAction.java:46)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:39)
        at org.gradle.api.internal.project.taskfactory.StandardTaskAction.execute(StandardTaskAction.java:26)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:801)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:768)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$1.run(ExecuteActionsTaskExecuter.java:131)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:300)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:292)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:174)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
        at org.gradle.internal.operations.DelegatingBuildOperationExecutor.run(DelegatingBuildOperationExecutor.java:31)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:120)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:99)
        ... 31 more

Seems like the constructor for GradleUpdateResult is getting a null release and the NPE occurs because of `release.class`:

```throw new IllegalStateException("ReleaseStatus subtype [" + release.class + "] not yet implemented")```

**Comment by ben-manes** [comment]
What happens when you use the previous commit hash?

**Comment by Blackbaud-JasonBodnar** [comment]
https://github.com/ben-manes/gradle-versions-plugin/commit/17aeb0cf52b4f14af152889978a98419f669ae0c appears to have introduced the bug as the commit before it (https://github.com/ben-manes/gradle-versions-plugin/commit/5640630d2cd2d10f6ea94f0e3f358d0e355cd006) works fine.

I'll see if I can figure out why it broke and come up with a fix.

**Comment by ben-manes** [comment]
Thanks! I'm sorry I'm not very helpful these days; the usual more work than time & energy.

**Comment by Blackbaud-JasonBodnar** [comment]
Seems that the problem is that in `buildGradleUpdateResults()` two lines changed:

```java
releaseCandidate: new GradleUpdateResult(gradleReleaseChannel == RELEASE_CANDIDATE.id, gradleUpdateChecker.runningGradleVersion, gradleUpdateChecker.releaseCandidateGradleVersion),
      nightly: new GradleUpdateResult(gradleReleaseChannel == RELEASE_CANDIDATE.id || gradleReleaseChannel == NIGHTLY.id, gradleUpdateChecker.runningGradleVersion, gradleUpdateChecker.nightlyGradleVersion)
```

Previously, the first parameter passed into `new GradleUpdateResult()` was the value of `enabled`. The commit in question changed that to be the value of `gradleReleaseChannel == RELEASE_CANDIDATE.id` and `gradleReleaseChannel == RELEASE_CANDIDATE.id || gradleReleaseChannel == NIGHTLY.id`. In my case, I have `dependencyUpdates.checkForGradleUpdate = false` in my build.gradle. I'm guessing that results in the last parameter of those constructors -- `gradleUpdateChecker.releaseCandidateGradleVersion` or `gradleUpdateChecker.nightlyGradleVersion` being `null` which causes the NPE in the constructor.

I don't quite understand what this change is supposed to do, but I'm guessing the first parameter needs to go back to included the value of `enabled` along with the additional clauses. Something like:

```java
releaseCandidate: new GradleUpdateResult(enabeld && (gradleReleaseChannel == RELEASE_CANDIDATE.id), gradleUpdateChecker.runningGradleVersion, gradleUpdateChecker.releaseCandidateGradleVersion),
      nightly: new GradleUpdateResult(enabled && (gradleReleaseChannel == RELEASE_CANDIDATE.id || gradleReleaseChannel == NIGHTLY.id), gradleUpdateChecker.runningGradleVersion, gradleUpdateChecker.nightlyGradleVersion)
```

That way if have `dependencyUpdates.checkForGradleUpdate = false` in your build.gradle (which in turn causes `enabled` to be `false` in the problematic code) `new GradleUpdateResult()` will always execute:

```java
if (!enabled) {
      this.version = ""
      this.isUpdateAvailable = false
      this.isFailure = false
      this.reason = "update check disabled"
    }
```
and never get to:

```java
throw new IllegalStateException("ReleaseStatus subtype [" + release.class + "] not yet implemented")
```
where `release` is `null` and the NPE occurs.

**Comment by ben-manes** [comment]
I agree, those statements are really long and therefore make the conditions seem confusing. Thank you for debugging and sending the fix.

**Pull request merged**
