### PR TITLE
Issue #509: Report Shows Same Dependencies With Different Actual Version in Current and Outdated Section; Issue #507: Report Misses Dependencies because of Unchecked Configurations

### PR DESCRIPTION
**Pull request by mroeppis**
**Issue #509: Report Shows Same Dependencies With Different Actual Version in Current and Outdated Section**
* implemented a filter for "none" versioned dependencies -> if there is another dependency with same group and artifact ID that has a concrete version then the none versioned dependency will be discarded -> "none" versions that pass the filter are assumed to have been declared without version by the user and must therefore be categorized "undeclared"
* added new report category "undeclared" -> dependencies that were declared without version are no longer categorized up-to-date
* added the new "undeclared" category to several test cases
* some new test resources had to be added for dependency resolution to succeed -> otherwise those would have been categorized "unresolved"
* I have thought long about the test case "Single project with flatDir repository" since this is about file dependencies. The thing is we assign a query dependency version "none" in this case which is why a latest version is not retrieved by Gradle. That's why we cannot tell if such a dependency is truly up-to-date. As for now such dependencies will be categorized "undeclared". Someday we might find a way to map file dependencies to G:A:V coordinates to perform a regular version check but that's out of scope right now
* there is one _limitation_, though: If a user declares a dependency without version and again (maybe in another project) with version then the one with version wins and the "none" versioned dependency won't be reported (...although it was explicitly declared by the user) -> however, a manual lookup of dependency occurences will be necessary anyway, so the loss of information should be minimal

**Issue #507: Report Misses Dependencies because of Unchecked Configurations**
* removed "isUsefulConfiguration" check -> from now on we analyze all configurations
* configuration resolution errors are logged at "info" -> this is motivated by the fact that Gradle itself triggers the error, so we simply document that behavior

### CODE REVIEW

**Review by ben-manes — APPROVED** [review]
This looks really good, thanks @mroeppis!

I tested it in our `examples/groovy` build, which incorrectly configured BOM dependencies. Those lack a version, so your new section comes out nicely. If fixed to `bom platform(...spring...)` then it resolves the implicit version and shows an upgrade, as intended.

You can merge and release this now that you have commit access. To release, simply update the version in [build.gradle](https://github.com/ben-manes/gradle-versions-plugin/blob/9bef5cb55bee63f2e51b3456c1172102cf4fb593/build.gradle#L14) and perform a github release. This will automatically [publish](https://github.com/ben-manes/gradle-versions-plugin/blob/master/.github/workflows/deploy.yml) to the plugin portal.

**Comment by mroeppis** [comment]
Thank you. I was wondering by the way when you could cut a new release. So it sounds good to read that.
I'd like to merge this but the page still says:

> Only those with write access to this repository can merge pull requests.

Could you please verify again?

**Comment by ben-manes** [comment]
It looks like you have not accepted the invitation yet. You should be able to visit the following link to accept.
https://github.com/ben-manes/gradle-versions-plugin/invitations

Screen Shot 2021-05-26 at 5 45 36 PM

**Comment by mroeppis** [comment]
Thanks. I must have overlooked that.

PR merged.

**Pull request merged**
