### PR TITLE
fix #704 can't modify unresolved.dependencies

### LINKED ISSUE #704: can't modify unresolved.dependencies
Starting from version **0.43.0** I can no longer modify the value of the `unresolved.dependencies` property.  
Example: https://github.com/jonathanlermitage/intellij-extra-icons-plugin/blob/master/build.gradle.kts#L178-L187  
```kotlin
withType<DependencyUpdatesTask> {
        outputFormatter = closureOf<Result> {
            unresolved.dependencies.removeIf {
                val coordinates = "${it.group}:${it.name}"
                coordinates.startsWith("unzipped.com") || coordinates.startsWith("com.jetbrains:ideaI")
            }
            val plainTextReporter = PlainTextReporter(project, revision, gradleReleaseChannel)
            val writer = StringWriter()
            plainTextReporter.write(writer, this)
            logger.quiet(writer.toString().trim())
        }
}
```
(I'm doing this because Gradle can't find some artifacts version, like com.jetbrains:ideaIU. This is not a blocker issue, this is purely cosmetic. I'm curious... ^_^)

Actually, Gradle's error is weird: I ran `gradlew dependencyUpdates` and I got this error:
```
./gradlew dependencyUpdates --warning-mode all

> Configure project :
e: /home/jon/prj/intellij-extra-icons-plugin/build.gradle.kts:179:37: Unresolved reference: removeIf
e: /home/jon/prj/intellij-extra-icons-plugin/build.gradle.kts:180:38: Unresolved reference: it
e: /home/jon/prj/intellij-extra-icons-plugin/build.gradle.kts:180:50: Unresolved reference: it
e: /home/jon/prj/intellij-extra-icons-plugin/build.gradle.kts:185:37: Type mismatch: inferred type is StringWriter but OutputStream was expected

FAILURE: Build failed with an exception.

* Where:
Build file '/home/jon/prj/intellij-extra-icons-plugin/build.gradle.kts' line: 179

* What went wrong:
Script compilation errors:

  Line 179:             unresolved.dependencies.removeIf {
                                                ^ Unresolved reference: removeIf

  Line 180:                 val coordinates = "${it.group}:${it.name}"
                                                 ^ Unresolved reference: it

  Line 180:                 val coordinates = "${it.group}:${it.name}"
                                                             ^ Unresolved reference: it

  Line 185:             plainTextReporter.write(writer, this)
                                                ^ Type mismatch: inferred type is StringWriter but OutputStream was expected

4 errors

```
Line 179 refers to `unresolved.dependencies.removeIf`.
It makes no sens. This is a SortedSet (I checked this with a debugger), so I should be able to invoke `removeIf`. I also tried to invoke `clear()`  and I faced the same issue. But it seems to be a Set, because I can iterate over this set with `foreach`.

Maybe this is a side effect of the recent Kotlin migration? Some Kotlin basic collections are immutable. The debugger says this is a SortedSet from java.util, but I already observed some bugs with JDK17 and Kotlin: some lists from java.util were silently replaced by their equivalent class from Kotlin standard lib; at least for methods which declares a List return type but actually returns a java.util.ArrayList. It made me crazy. I finally fixed this by replacing the java.util.list return type by java.util.ArrayList, and replacing star imports of java.util by single-class imports, otherwise Kotlin seemed to pick the ArrayList from the Kotlin standard lib instead of java.util.*. It was super weird because it did not fail at compile-time, but at runtime, with Java17 only (no problem with Java11): _ArrayList from Kotlin std lib couldn't be casted to java.util.ArrayList_ ^_^.

### PR DESCRIPTION
**Pull request by jonathanlermitage**
Closes https://github.com/ben-manes/gradle-versions-plugin/issues/704

@ben-manes

### CODE REVIEW

**Comment by ben-manes** [comment]
This looks really good, thanks! Do you want to try adding a test case to avoid future regressions? If not then I'll merge and release.

**Comment by jonathanlermitage** [comment]
Good idea, I will look at this.

**Comment by jonathanlermitage** [comment]
Test case added.

**Comment by ben-manes** [comment]
wonderful, thanks! I triggered a [release](https://github.com/ben-manes/gradle-versions-plugin/actions/runs/3449907015).

**Pull request merged**
