### PR TITLE
Add dependency-submission workflow and address deprecations/vulnerabilities

### PR DESCRIPTION
**Pull request by bigdaz**
- Updates workflows to use Node20-compatible actions where available
- Switches from `gradle/gradle-build-action` to `gradle/actions/setup-gradle`
- Adds a workflow using `gradle/actions/dependency-submission` to generate and upload dependency-graph
- Bumps the version of the 'ktlint' plugin to address reported vulnerability

### CODE REVIEW

**Comment by ben-manes** [comment]
oh, looks like a bunch of klint style issues. Is there a way to let it auto-fix?

**Comment by ben-manes** [comment]
thanks as always!

**Comment by bigdaz** [comment]
Sorry, I know absolutely zero about the `ktlint` plugin. I guess the new version has more checks?

I can remove that "fix" for now, so we get the rest of the changes through.

**Comment by ben-manes** [comment]
oh no worries, I don't know it either. I found the its auto format task, fixed where it wouldn't do it automatically, and merged this all in. thanks again!

**Pull request merged**
