### PR TITLE
[WIP] Migrate to Kotlin - Part 1

### PR DESCRIPTION
**Pull request by jaredsburrows**
- Add temporary `api` module to convert code to Kotlin
- Can't mix Groovy and Kotlin together, easier to make separate module
- Keep tests in Groovy for Spock

Pushing commits here for conversion and CI

@ben-manes

### CODE REVIEW

**Review by ben-manes — APPROVED** [review]

**Comment by jaredsburrows** [comment]
@ben-manes `git mv` does not need to keep the history. Is there a better way?

**Comment by ben-manes** [comment]
Unfortunately my understanding is that is the best available and by design doesn't handle history elegantly. One can figure it out by using `git log --follow`, or just spelunking through prior commits / tags.

**Comment by jaredsburrows** [comment]
@ben-manes I think this is enough for a first pass or "part 1"?

**Comment by ben-manes** [comment]
cool! 🙂

**Pull request merged**
