### PR TITLE
Major refactoring of versions plugin

### PR DESCRIPTION
**Pull request by ben-manes**
@jochenberger 

This is work in progress, but ready for discussion. The pending tasks are making all tests pass and removing boilerplate adaption code for passing the results into the reporter. These changes should help in addressing #28, #30, #61, and #62.

Most of the changes are cosmetic. The plugin was originally written in a scripting language approach (short but untyped). That coding style became awkward when converted to be type-safe, so it has been refactored to be more Java like.

Rather than using a detached configuration of all project dependencies, each configuration is copied and resolved independently. This should honor the configuration's resolution strategy (#28) and list each dependency version as an entry (#62). This also lets us decide whether to continue to resolve configurations with all repositories or only those associated with the given configuration. That would avoid suppressing problematic repositories (#30), such as the quirks caused by the plugin repository (#61).

Using resolution strategies or component rules may make it possible to add revision exclusions like "beta" and "rc" to the report (#25, #31). This could now be done in user code, and later evolved as a plugin configuration. #40 shows some promise and could be revived.

Performance should remain similar due to the Gradle cache making duplicate resolutions no-ops.

### CODE REVIEW

**Comment by ben-manes** [comment]
All tests passing

**Comment by ben-manes** [comment]
I think I'll defer refactoring the report to avoid the adapter code to another commit. The changes are now in a state ready to merge after discussion.

**Comment by ben-manes** [comment]
I had some promising results [experimenting](https://discuss.gradle.org/t/excessive-downloads-during-resolution/10193/7) with component rules. Unfortunately it doesn't work correctly with `latest.${revision}`, but does fine with `+`. It may make sense to use `+` and then check the metadata status for backwards compatibility.

**Comment by ben-manes** [comment]
@jochenberger 

Can you please merge this and release? I switched to `+` and it works beautifully with custom rules to reject a release candidate.

**Comment by jochenberger** [comment]
Sorry, I haven't found the time to have a closer look, but I'll create a release right away.

**Comment by ben-manes** [comment]
No problem, I got excited by the component rules working. So I pushed a release using my maven central account, which should sync with jcenter. My only concern is that the plugin portal may not be updated, but then users will realize when they run the task, right? ;-)

**Comment by jochenberger** [comment]
I created the 0.11.1 release in JCenter, syncing from Maven Central does not seem to work reliably anyway. The new version should show up at https://plugins.gradle.org/plugin/com.github.ben-manes.versions soon.

**Comment by ben-manes** [comment]
Thanks!

**Comment by jochenberger** [comment]
Sorry, but I guess, we may need a 0.11.4. ;-)
I just got the advise to upgrade a library from 0.3.0 to 0.3.0. My project has a direct dependency on 0.1.2 and a transitive one on 0.3.0 and 0.3.0 is the latest version available, so it seems to be only a reporting issue.

**Comment by ben-manes** [comment]
Does the report say `[0.1.2 -> 0.3.0]` or `[0.3.0 -> 0.3.0]`? If the former then would this be due to telling Gradle to not resolve a configuration transitively?

**Comment by jochenberger** [comment]
It does indeed say `[0.3.0 -> 0.3.0]`. And both versions belong to the same configuration (compile). As far as I remember, previous versions of the plugin listed the library as up-to-date. But that might also be related to the new Gradle release candidate. I will have another look tomorrow, I'm AFK for today.

**Comment by ben-manes** [comment]
Great, have a good evening. I've got to do the day job stuff anyways =)

**Comment by jochenberger** [comment]
Alright, that's strange. It says `[0.3.0 -> 0.3.0]` in all the 0.11.x versions. 0.10.1 says that the library is up-to-date at 0.3.0 (which is the version that is actually used but not the one from the build file).

**Comment by jochenberger** [comment]
Alright, it's related to my multi-project setup. The root project has a dependency on 0.1.2, a subproject depends on 0.3.0 (don't ask...).

**Comment by ben-manes** [comment]
I wonder why this only shows up on 0.11.x and not previous releases.

The old approach grabbed all dependencies across all configurations. The new way resolves each configuration independently. So it should have been pulled in, perhaps inappropriately, by both.

**Comment by ben-manes** [comment]
I'm going to try to fix the issues you found over the weekend. I'll try to find a few large Gradle projects to test on as well, to see if I can wrangle out a few other issues. Sorry for springing this on you out of the blue.

**Comment by jochenberger** [comment]
No worries, it's fun to work on the plugin, there's always a lot to learn for me.
Maybe we should also try to increase the test coverage. I know that I've been quite lazy when it comes to writing tests...

**Comment by ben-manes** [comment]
I fixed the `jacoco` dependency that you observed. It appears that Gradle hides some dependencies by not listing them in `configuration.dependencies` but they appear in the resolved set. That set is now filtered by the declared listing.

**Comment by ben-manes** [comment]
Tested snapshot on
* Hibernate
* Spring
* Grails
* Forkhubs (android)
* cgeo (android)

The results look good and performance is comparable to the previous release.

**Comment by jochenberger** [comment]
I just tested a snapshot, it still shows the jacoco and pmd libraries.

**Comment by ben-manes** [comment]
hmm, I swore I had that fixed. Thanks, I'll take another look.

**Comment by ben-manes** [comment]
Okay, I think I got it this time.

**Comment by jochenberger** [comment]
Yes, looks good now, thanks!

**Pull request merged**
