### PR TITLE
Fix resolution strategy for Groovy.

### PR DESCRIPTION
**Pull request by johnjohndoe**
+ Before no versions were output.
+ This fix is based on the discussion in https://github.com/ben-manes/gradle-versions-plugin/issues/344.

---

@timja @jmfayard @bric3 Please review this fix.

### CODE REVIEW

**Comment by jmfayard** [comment]
Lgtm

**Comment by johnjohndoe** [comment]
@timja I agree. It is not obvious from the splitted code snippets in the README that the `isNonStable` variable can be defined in the `dependencyUpdates` block. However, it can. I tested both options. If `isNonStable` is defined outside the `dependencyUpdates` block then it works as described. If `isNonStable`  is defined inside the `dependencyUpdates` block then `it` has to be replaced with `qualifier` to avoid conflicts with another `it`.
I personally prefer to **limit the scope** the variable inside the `dependencyUpdates` block. 
For this pull request I decided that this should be discussed separately.

**Comment by ben-manes** [comment]
Thanks!

**Comment by bric3** [comment]
I would have the example split. But this looks good to me.

**Comment by ben-manes** [comment]
Happy to accept a PR if you'd like improvements :)

**Comment by bric3** [comment]
I know, I know 😉

**Pull request merged**
