### PR TITLE
Issue#201: Resolve versions in parallel

### PR DESCRIPTION
**Pull request by rpau**
This patch resolves configurations in parallel using
gpars.

### CODE REVIEW

**Comment by ben-manes** [comment]
Thanks! Is there a reason you used gpars instead of Gradle’s worker api?
https://guides.gradle.org/using-the-worker-api/

**Comment by rpau** [comment]
Yes, simplicity :) and because is the most widely used library for parallelizing collections in groovy.

**Comment by ben-manes** [comment]
Maybe @bigdaz can chime in. Is there a pro/con of using Gradle’s worker api for a plugin versus gpars? Can workers be used in a backward compatible way, e.g. is injection optional and null check if the manager is absent?

@rpau I don't have a strong opinion, except concern that a Gradle facility might be better for some unknown implementation reason.

**Comment by ben-manes** [comment]
rebased and merged, thanks!

**Comment by ben-manes** [comment]
I tweaked your implementation a bit to parallelize all configurations across all projects, rather than process each project in lock-step.

**Pull request closed without merging**
