### PR TITLE
gradle 7.4.2

### PR DESCRIPTION
**Pull request by jaredsburrows**
- Gradle 7.4.2
 - Removed `com.github.ben-manes.versions.properties`
```
Caused by: org.gradle.api.InvalidUserCodeException: Entry META-INF/gradle-plugins/com.github.ben-manes.versions.properties is a duplicate but no duplicate handling strategy has been set. Please refer to https://docs.gradle.org/7.4.2/dsl/org.gradle.api.tasks.Copy.html#org.gradle.api.tasks.Copy:duplicatesStrategy for details.
```

@ben-manes

### CODE REVIEW

**Comment by jaredsburrows** [comment]
@ben-manes not sure what to do about 
```
> Receiver class com.github.benmanes.gradle.versions.updates.Coordinate does not define or inherit an implementation of the resolved method 'abstract java.lang.Object getProperty(java.lang.String)' of interface groovy.lang.GroovyObject.
```

**Comment by ben-manes** [comment]
I'm not sure. The simplest might be to make it a Java class as it is just a simple data holder.

**Comment by jaredsburrows** [comment]
@ben-manes Are you open to more pure Java sources in this repo? Maybe long term, we can rewrite to Kotlin :)

**Comment by ben-manes** [comment]
yeah, that's fine. I don't know Groovy beyond just figuring out how to write the plugins back when that was Gradle's preferred option. I'm not opinionated, with the only minor caveat that I haven't worked with kotlin but that makes it mostly equivalent to my Groovy expertise.

**Comment by jaredsburrows** [comment]
@ben-manes Finally this is now passing :)

**Review by ben-manes — APPROVED** [review]

**Pull request merged**
