### PR TITLE
Official Gradle Wrapper Validation GitHub Action

### PR DESCRIPTION
**Pull request by JLLeitschuh**
See: https://github.com/gradle/wrapper-validation-action

### CODE REVIEW

**Comment by ben-manes** [comment]
thanks!

**Comment by ben-manes** [comment]
Looks like it failed to setup the job?

https://github.com/ben-manes/gradle-versions-plugin/commit/be05fde714e42adba61d94d4474c80b5a27290dc/checks?check_suite_id=403053837

**Comment by JLLeitschuh** [comment]
Can you try re-running? If it doesn't work, I'll report something to GitHub

**Comment by ben-manes** [comment]
no luck

Screen Shot 2020-01-15 at 3 37 02 PM

**Comment by JLLeitschuh** [comment]
Here's the issue:
https://github.com/actions/checkout/issues/137

**Comment by friederbluemle** [comment]
Nice 👏

**Pull request merged**
